package com.ywy.erp.entities;

import java.math.BigDecimal;

public class Depot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depot.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depot.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depot.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depot.warehousing
     *
     * @mbggenerated
     */
    private BigDecimal warehousing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depot.truckage
     *
     * @mbggenerated
     */
    private BigDecimal truckage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depot.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depot.sort
     *
     * @mbggenerated
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depot.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depot.principal
     *
     * @mbggenerated
     */
    private Long principal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depot.tenant_id
     *
     * @mbggenerated
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depot.delete_Flag
     *
     * @mbggenerated
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depot.is_default
     *
     * @mbggenerated
     */
    private Boolean isDefault;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depot.id
     *
     * @return the value of depot.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depot.id
     *
     * @param id the value for depot.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depot.name
     *
     * @return the value of depot.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depot.name
     *
     * @param name the value for depot.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depot.address
     *
     * @return the value of depot.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depot.address
     *
     * @param address the value for depot.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depot.warehousing
     *
     * @return the value of depot.warehousing
     *
     * @mbggenerated
     */
    public BigDecimal getWarehousing() {
        return warehousing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depot.warehousing
     *
     * @param warehousing the value for depot.warehousing
     *
     * @mbggenerated
     */
    public void setWarehousing(BigDecimal warehousing) {
        this.warehousing = warehousing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depot.truckage
     *
     * @return the value of depot.truckage
     *
     * @mbggenerated
     */
    public BigDecimal getTruckage() {
        return truckage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depot.truckage
     *
     * @param truckage the value for depot.truckage
     *
     * @mbggenerated
     */
    public void setTruckage(BigDecimal truckage) {
        this.truckage = truckage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depot.type
     *
     * @return the value of depot.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depot.type
     *
     * @param type the value for depot.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depot.sort
     *
     * @return the value of depot.sort
     *
     * @mbggenerated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depot.sort
     *
     * @param sort the value for depot.sort
     *
     * @mbggenerated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depot.remark
     *
     * @return the value of depot.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depot.remark
     *
     * @param remark the value for depot.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depot.principal
     *
     * @return the value of depot.principal
     *
     * @mbggenerated
     */
    public Long getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depot.principal
     *
     * @param principal the value for depot.principal
     *
     * @mbggenerated
     */
    public void setPrincipal(Long principal) {
        this.principal = principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depot.tenant_id
     *
     * @return the value of depot.tenant_id
     *
     * @mbggenerated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depot.tenant_id
     *
     * @param tenantId the value for depot.tenant_id
     *
     * @mbggenerated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depot.delete_Flag
     *
     * @return the value of depot.delete_Flag
     *
     * @mbggenerated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depot.delete_Flag
     *
     * @param deleteFlag the value for depot.delete_Flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depot.is_default
     *
     * @return the value of depot.is_default
     *
     * @mbggenerated
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depot.is_default
     *
     * @param isDefault the value for depot.is_default
     *
     * @mbggenerated
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }
}